language: java

jdk:
  - oraclejdk8
  - openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - cd back && ./gradlew assemble cd ../

script:
  - cd back && ./gradlew check

notifications:
  email:
    on_failure: change