version: '3'

services:
  es:
    image: elasticsearch:2.4.5
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - coddy
  coddy:
    image: crunchytorch/coddy
    depends_on:
      - es
    networks:
      - coddy
      - gfe
    labels:
      - "traefik.enable=true"
      - "traefik.backend=coddy"
      - "traefik.frontend.rule=Host:coddy.crunchytorch.fr"
      - "traefik.docker.network=gfe"
networks:
  gfe:
    external:
      name: gfe
  coddy: ~